version: '3'
services:
  client:
    restart: on-failure
    build:
      context: ./emaily-app-client
      dockerfile: dockerfile
    depends_on:
      - api
    ports:
      - 8888:8888
    env_file:
      - ./emaily-app-client/.env.production
  api:
    restart: on-failure
    build:
      context: ./emaily-app-server
      dockerfile: dockerfile
    env_file:
      - ./emaily-app-server/.env.production
