version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./emaily-app-nginx
      dockerfile: dev.dockerfile
    ports:
      - 8080:80
    command: |
      sh -c
        "./wait-for.sh client:3000 api:5000 -- nginx -g \"daemon off;\""
  client:
    restart: on-failure
    build:
      context: ./emaily-app-client
      dockerfile: dev.dockerfile
    volumes:
      - /app/.git
      - /app/node_modules
      - ./emaily-app-client:/app
  api:
    restart: on-failure
    build:
      context: ./emaily-app-server
      dockerfile: dev.dockerfile
    depends_on:
      - db
    volumes:
      - /app/.git
      - /app/node_modules
      - ./emaily-app-server:/app
    env_file:
      - ./emaily-app-server/.env.development
    command: |
      sh -c 
        "./wait-for.sh db:27017 -- npm run start-dev"
  db:
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./emaily-app-db/dbdata:/data/db
