version: '3'
services:
  proxy:
    restart: always
    build:
      context: ./proxy
      dockerfile: dev.dockerfile
    ports:
      - 8080:80
    command: |
      sh -c
        "./wait-for.sh client:3000 api:5000 -- nginx -g \"daemon off;\""
  client:
    restart: on-failure
    build:
      context: ./client
      dockerfile: dev.dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    restart: on-failure
    build:
      context: ./api
      dockerfile: dev.dockerfile
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - ./api/.env.development
    command: |
      sh -c 
        "./wait-for.sh db:27017 -- npm run start-dev"
  db:
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./db/dbdata:/data/db
