version: '3'
services:
  client:
    restart: on-failure
    build:
      context: client
    depends_on:
      - api
    ports:
      - 8888:8888
    env_file:
      - client/.env.production
  api:
    restart: on-failure
    build:
      context: ./api
    env_file:
      - api/.env.production
